# Generated by Django 3.2.9 on 2021-12-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesos',
            fields=[
                ('id_acceso', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'accesos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cantones',
            fields=[
                ('id_canton', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.BooleanField()),
                ('us_ingreso', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateTimeField()),
                ('us_modificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cantones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Captores',
            fields=[
                ('id_captor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'captores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CaptoresTipos',
            fields=[
                ('id_captor_tipo', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'captores_tipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('us_ingreso', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateTimeField()),
                ('us_modificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuencas',
            fields=[
                ('codigo', models.CharField(blank=True, max_length=8, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
                ('id_cuenca', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nivel', models.IntegerField(blank=True, null=True)),
                ('us_ingreso', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateTimeField()),
                ('us_modificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cuencas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionesViento',
            fields=[
                ('id_dir_viento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('abreviacion', models.CharField(max_length=5)),
                ('grados', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'direcciones_viento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Distritos',
            fields=[
                ('id_distrito', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=600)),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('us_ingreso', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateTimeField()),
                ('us_modificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'distritos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estaciones',
            fields=[
                ('id_estacion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_levantamiento', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('informacion', models.TextField(blank=True, null=True)),
                ('dataloger', models.TextField(blank=True, null=True)),
                ('img_norte', models.BinaryField(blank=True, null=True)),
                ('img_sur', models.BinaryField(blank=True, null=True)),
                ('img_este', models.BinaryField(blank=True, null=True)),
                ('img_oeste', models.BinaryField(blank=True, null=True)),
                ('vista_interna', models.BooleanField(blank=True, null=True)),
                ('vista_externa', models.BooleanField(blank=True, null=True)),
                ('us_ingreso', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_ingreso1', models.DateTimeField(blank=True, null=True)),
                ('us_modificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosEstacion',
            fields=[
                ('id_estado_estacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'estados_estacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosValidacion',
            fields=[
                ('id_estado_validacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'estados_validacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FenomenosNaturales',
            fields=[
                ('id_fen_nat', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(blank=True, max_length=110, null=True)),
                ('icono', models.BinaryField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('us_ingreso', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateTimeField()),
                ('us_modificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fenomenos_naturales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneroNubes',
            fields=[
                ('id_genero_nube', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('icono', models.BinaryField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('us_ingreso', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateTimeField()),
                ('us_modificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('cifrado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genero_nubes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodosAcceso',
            fields=[
                ('id_metodo_acceso', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'metodos_acceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parroquias',
            fields=[
                ('id_parroquia', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.BooleanField()),
                ('us_ingreso', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateTimeField()),
                ('us_modificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parroquias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfundidadesGeotemp',
            fields=[
                ('id_profundidad_geotemp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'profundidades_geotemp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propietarios',
            fields=[
                ('id_propietario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('representante', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('informe', models.CharField(blank=True, max_length=100, null=True)),
                ('us_ingreso', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateTimeField()),
                ('us_modificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'propietarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id_provincia', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
                ('us_ingreso', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateTimeField()),
                ('us_modificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'provincias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntosObservacion',
            fields=[
                ('id_punto_obs', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('img_norte', models.BinaryField(blank=True, null=True)),
                ('img_sur', models.BinaryField(blank=True, null=True)),
                ('img_este', models.BinaryField(blank=True, null=True)),
                ('img_oeste', models.BinaryField(blank=True, null=True)),
                ('estado', models.BooleanField()),
                ('us_ingreso', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateTimeField()),
                ('us_modificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'puntos_observacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regiones',
            fields=[
                ('id_region', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
                ('us_ingreso', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateTimeField()),
                ('us_modificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'regiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEstaciones',
            fields=[
                ('id_tipo_estacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField()),
                ('us_ingreso', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateTimeField()),
                ('us_modificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'tipo_estaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoGeotemperaturas',
            fields=[
                ('id_tipo_geotemp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'tipo_geotemperaturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposCalculoEvap',
            fields=[
                ('id_tipo_calculo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipos_calculo_evap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('id_unidad_medida', models.IntegerField(primary_key=True, serialize=False)),
                ('simbolo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('us_ingreso', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('us_modificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unidades_medida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('contrasenia', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('persona_fk', models.BigIntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
                ('conv', models.BooleanField()),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='v1073161H',
            fields=[
                ('id_temp_int_baro', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_1073161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='v1073161HVal',
            fields=[
                ('id_temp_int_baro_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_1073161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V1087161H',
            fields=[
                ('id_pres_corre', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'db_table': '_1087161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V1087161HVal',
            fields=[
                ('id_pres_corre_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'db_table': '_1087161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V1097161H',
            fields=[
                ('id_pres_conv', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'db_table': '_1097161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V1097161HVal',
            fields=[
                ('id_pres_conv_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'db_table': '_1097161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V1263011H',
            fields=[
                ('id_caudal_max_hor', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_1263011h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V1263011HVal',
            fields=[
                ('id_caudal_max_hor_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_1263011h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V12630161H',
            fields=[
                ('id_caudal_ins_hor', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_12630161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V12630161HVal',
            fields=[
                ('id_caudal_ins_hor_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_12630161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V1263021H',
            fields=[
                ('id_caudal_min_hor', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_1263021h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V1263021HVal',
            fields=[
                ('id_caudal_min_hor_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_1263021h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V1263041H',
            fields=[
                ('id_caudal_prom_hor', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_1263041h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V1263041HVal',
            fields=[
                ('id_caudal_prom_hor_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_1263041h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V141011H',
            fields=[
                ('id_nivelagua_max_hor', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_141011h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V141011HVal',
            fields=[
                ('id_nivelagua_max_hor_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_141011h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V1410161H',
            fields=[
                ('id_nivelagua_ins_hor', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_1410161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V1410161HVal',
            fields=[
                ('id_nivelagua_ins_hor_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_1410161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V141021H',
            fields=[
                ('id_nivelagua_min_hor', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_141021h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V141021HVal',
            fields=[
                ('id_nivelagua_min_hor_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_141021h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V141041H',
            fields=[
                ('id_nivelagua_prom_hor', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_141041h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V141041HVal',
            fields=[
                ('id_nivelagua_prom_hor_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_141041h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V1714161H',
            fields=[
                ('id_prec_1h', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_1714161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V1714161HVal',
            fields=[
                ('id_prec_1h_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_1714161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V171481H',
            fields=[
                ('id_prec', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_171481h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V171481HVal',
            fields=[
                ('id_prec_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_171481h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V187161H',
            fields=[
                ('id_presion', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'db_table': '_187161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V187161HVal',
            fields=[
                ('id_presion_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'db_table': '_187161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V272981H',
            fields=[
                ('id_viento_rec', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
            ],
            options={
                'db_table': '_272981h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V272981HVal',
            fields=[
                ('id_viento_rec_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
            ],
            options={
                'db_table': '_272981h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V29311H',
            fields=[
                ('id_temp_aire_max', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_29311h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V29311HVal',
            fields=[
                ('id_temp_aire_max_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_29311h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V29321H',
            fields=[
                ('id_temp_aire_min', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_29321h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V29321HVal',
            fields=[
                ('id_temp_aire_min_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_29321h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V303161H',
            fields=[
                ('id_temp_agua_mar', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_303161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V303161HVal',
            fields=[
                ('id_temp_agua_mar_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_303161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V42161H',
            fields=[
                ('id_viento_dir', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('id_dir_viento', models.IntegerField()),
                ('valor', models.IntegerField()),
            ],
            options={
                'db_table': '_42161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V42161HVal',
            fields=[
                ('id_viento_dir_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('id_dir_viento', models.IntegerField()),
            ],
            options={
                'db_table': '_42161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V557161H',
            fields=[
                ('id_pres_red', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'db_table': '_557161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V557161HVal',
            fields=[
                ('id_pres_red_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'db_table': '_557161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V573161H',
            fields=[
                ('id_term_seco', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_573161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V573161HVal',
            fields=[
                ('id_term_seco_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_573161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V583161H',
            fields=[
                ('id_term_hmd', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_583161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V583161HVal',
            fields=[
                ('id_term_hmd_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_583161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V597161H',
            fields=[
                ('id_tension_vapor', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'db_table': '_597161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V597161HVal',
            fields=[
                ('id_tension_vapor_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'db_table': '_597161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V603161H',
            fields=[
                ('id_punto_rocio', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_603161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V603161HVal',
            fields=[
                ('id_punto_rocio_val', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_603161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V614161H',
            fields=[
                ('id_evapo', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_614161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V614161HVal',
            fields=[
                ('id_evapo_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_614161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V644161H',
            fields=[
                ('id_nube', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('altura_suelo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '_644161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V644161HVal',
            fields=[
                ('id_nube_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('altura_suelo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '_644161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V674161H',
            fields=[
                ('id_nube', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('altura_suelo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '_674161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V674161HVal',
            fields=[
                ('id_nube_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('altura_suelo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '_674161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V704161H',
            fields=[
                ('id_nube', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('altura_suelo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '_704161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V704161HVal',
            fields=[
                ('id_nube_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('altura_suelo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '_704161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V7229161H',
            fields=[
                ('id_visibilidad_hor', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_7229161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V7229161HVal',
            fields=[
                ('id_visibilidad_hor_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_7229161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V7514161H',
            fields=[
                ('id_reduc_tanque', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_7514161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V7514161HVal',
            fields=[
                ('id_reduc_tanque_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_7514161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V765161H',
            fields=[
                ('id_agua_sacada', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_765161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V765161HVal',
            fields=[
                ('id_agua_sacada_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_765161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V775161H',
            fields=[
                ('id_agua_aniadida', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_775161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V775161HVal',
            fields=[
                ('id_agua_aniadida_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': '_775161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V91161H',
            fields=[
                ('id_humedad_rltva', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('id_unidad_medida', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha_toma', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '_91161h',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V91161HVal',
            fields=[
                ('id_humedad_rltva_val', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('valor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '_91161h_val',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id_zona', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('us_ingreso', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateTimeField()),
                ('us_modificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zonas',
                'managed': False,
            },
        ),
    ]
